# Generated by Django 4.1.2 on 2022-10-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0002_remove_permit_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
